language: node_js
node_js:
  - '8'
install: ./build/npm-install.sh
script:
  - npm run deploy
after_script:
  - node ./node_modules/coveralls/bin/coveralls.js -v < ./reports/report-lcov/lcov.info
sudo: required
deploy:
  - provider: npm
    skip_cleanup: true
    email: comindware-awesome-bot@comindware.com
    api_key:
      secure: EKJsVIsPEuYKRB9Dani3eSkWuLk8WUU9eVs0rG4ai1ga4lXSEYaZSnGsyRoG91fEbVCIs+eictbdKs8AKN4hNbe/4p99hPtqiRjuIkS/KQl/lF313l6B2Tn8YLM9TpoKG2O0QY/+m7Zd8yCwu1AR7PYCt60UOrFRNtSGt8HHuJF38epEha0JyJ4e2xQIWZSAi6mRPvJ3mIOQ0SLYoAnUHT7u9x+VFbXhcfZ01c2/pokYFKo0ERFSGUR4W+N25T8HLHnQ9OpL0xXjYLnbOvUVbX/+3hfWQZ9OnQlLl74LKwPoqHZS1rQmoq9J+Xsc/sWp1xcCVscYaHFB4/QtWtIJ+s03G5ZU6Q+UJUfF5YvUDBuetdq+rizW8WnvhiCs6KYYp2gb8Qya4twnnsymlS2iVckiHdM5qj+4LxI/9o57AmYqBdKsE+p6Zo6hDqpIKG/3H51C2jeey4kUPCfw5Ux0Jjy6yBioP2dSgOHTp/4qZ//wR70QvIN8RQzh3FiQTW+ntBtyuevJ+o40it/RZvyaJr8P9r0bGnhL6cWNUpCeSe+9vfDlgI5xBt8jRGBT3kO1/DHJqsJWjClLhPJNxgxgOg22kSJ/+/eMRpUtiPPZl5V0Rvu4Lfd36dqoD2cnM5TwLwhjZ2OEd2LcJ1Pzlzpwjpek/HOLRimUC4y+rxUwCSU=
    on:
      tags: true
      repo: comindware/core-ui
      branch: 1.4/release
  - provider: script
    script: npm run deploy:pages
    skip_cleanup: true
    on:
      tags: true
      repo: comindware/core-ui
      branch: 1.4/release
addons:
  firefox: "latest"